# Generated by Django 4.0.6 on 2022-07-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_alter_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="My Freakin' Awesome Blog !!!!", max_length=255),
        ),
    ]
